TCBSistemaDeControle/Controllers/FuncionariosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using TCBSistemaDeControle.Data;
using TCBSistemaDeControle.Models;
using TCBSistemaDeControle.Repositories;

namespace TCBSistemaDeControle.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IFuncionariosRepositorio funcionariosRepositorio;

        public FuncionariosController(ApplicationDbContext db, IFuncionariosRepositorio _funcionariosRepositorio)
        {
            this.db = db;
            this.funcionariosRepositorio = _funcionariosRepositorio;
        }

        public int sessionIdUsuario
        {
            get
            {
                int sessionIdUsuario = 0;
                if (HttpContext.Session.GetInt32("Id") != null)
                    sessionIdUsuario = (int)HttpContext.Session.GetInt32("Id");
                return sessionIdUsuario;
            }
        }

        public IActionResult Index(int id)
        {
            var idUsuario = HttpContext.Session.GetInt32("idUsuario");
            if (idUsuario == null) return RedirectToAction("Index", "Login");

            var dbconsult = db.Usuarios
                .AsNoTracking()
                .FirstOrDefault(u => u.Id == idUsuario && u.Hash == HttpContext.Session.GetString("hash"));

            if (dbconsult == null) return RedirectToAction("Index", "Login");

            var sessionIdUsuario = dbconsult.Id;

            var setor = db.Setores.FirstOrDefault(s => s.Id == id);
            if (setor == null)
            {
                TempData["MensagemErro"] = $"{dbconsult.NomeCompleto}, o setor selecionado não foi encontrado";
                return RedirectToAction("Setores","Index");
            }

            var funcionarios = db.Funcionarios
                .Where(f => f.SetorId == id)
                .ToList();


            // ---------------------------------------------------------- quantidade de funcionarios por setor

            var viewModel = new FuncionariosPorSetorViewModel
            {
                SetorId = setor.Id,
                NomeSetor = setor.Nome,
                Funcionarios = funcionarios,
                Quantidade = funcionarios.Count()
            };

            ViewBag.NomeCompleto = dbconsult.NomeCompleto;
            ViewBag.Email = dbconsult.Email;
            ViewBag.TipoPerfil = dbconsult.TipoPerfil;

            return View(viewModel);
        }
    }
}

TCBSistemaDeControle/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using TCBSistemaDeControle.Data;
using TCBSistemaDeControle.Models;
using TCBSistemaDeControle.Helper;

namespace TCBSistemaDeControle.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext db;

        public LoginController(ApplicationDbContext _db)
        {
            db = _db;
        }   

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string email, string senha)
        {
            var usuario = db.Usuarios.FirstOrDefault(u => u.Email == email);

            try
            {
                if (usuario != null)
                {
                    var senhaHash = Utilitarios.GerarHashSenha(senha, usuario.Salt);

                    if (senhaHash == usuario.Senha)
                    {
                        string hash = Utilitarios.GeradorHash();

                        usuario.Hash = hash;
                        db.SaveChanges();

                        HttpContext.Session.SetInt32("idUsuario", usuario.Id);
                        HttpContext.Session.SetString("hash", hash);

                        TempData["MensagemSucesso"] = $"Seja bem-vindo {usuario.NomeCompleto}";
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        TempData["MensagemErro"] = $"E-mail ou senha incorretos!";
                        return View("Index");
                    }
                }

                TempData["MensagemErro"] = $"Ops, usuário não encontrado!";
                return View("Index");
            }
            catch (Exception e)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos realizar seu login, tente novamente. Detalhe do erro: {e.Message}";
                return RedirectToAction("Index");
            }
        }

        public string idUsuario { get; set; }
        public string hash { get; set; }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "LandingPage");
        }
    }
}

TCBSistemaDeControle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TCBSistemaDeControle.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
    rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/v/dt/dt-2.0.8/datatables.min.css" rel="stylesheet">

    <link href="~/css/shared.css" rel="stylesheet" />
</head>
<body>
    <header class="d-flex justify-content-between align-items-center p-3 bg-dark border-bottom shadow-sm" style="position:fixed; width:100%; z-index: 10000000; background:black;">
        <!-- Botão do menu lateral -->
        <button class="btn botao-menu" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions" >
            <i class="bi bi-three-dots" style="font-size:25px;"></i>
        </button>

        <!-- Offcanvas Menu -->
        <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
            <div class="offcanvas-header" >
                <a  class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">
                    <h3>TCB</h3>
                </a>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">

                <!-- Dropdown de usuário -->
                <div class="dropdown">
                    <img src="https://i.ibb.co/DPymZqqd/image-removebg-preview-1.png" alt="Avatar" class="rounded-circle" />
                    <div class="flex-user-body" >
                        <span class="me-2 nome-user" data-bs-toggle="dropdown" aria-expanded="false">Olá, @ViewBag.NomeCompleto!</span>
                        @if(ViewBag.TipoPerfil == 1)
                        {
                            <span class="me-2" style="color:gray; font-weight:bold;font-size:.8rem;" data-bs-toggle="dropdown" aria-expanded="false">Administrador <span><i class="bi bi-caret-down-fill"></i></span></span>
                        }
                        else
                        {
                            <span class="me-2" style="color:gray; font-weight:bold;font-size:.8rem;" data-bs-toggle="dropdown" aria-expanded="false">Lider <span><i class="bi bi-caret-down-fill"></i></span></span>
                        }
                        <ul class="dropdown-menu dropdown-menu-end">
                                <li>
                                    <a class="dropdown-item" asp-controller="Login" asp-action="Logout">
                                        <i class="bi bi-box-arrow-right me-2"></i> Sair
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Usuario" asp-action="AtualizarSenha">
                                        <i class="bi bi-key-fill me-2"></i> Alterar Senha
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Usuario" asp-action="MeusDados">
                                        <i class="bi bi-person-fill me-2"></i> Meus Dados
                                    </a>
                                </li>
                            </ul>
                    </div>
                </div>
                    <hr />
                    <ul class="nav flex-column">
                 
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house"></i> Página Inicial</a>
                        </li>

                        @if(ViewBag.TipoPerfil == 1)
                        {
                            <div class="accordion accordion-flush" id="accordionSetores">
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOneSetores" aria-expanded="false" aria-controls="flush-collapseOne">
                                            <i class="bi bi-building" style="padding-right:5px;"></i> Setores
                                        </button>
                                    </h2>
                                    <div id="flush-collapseOneSetores" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                                        <ul class="list-unstyled">
                                            <li>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Setores" asp-action="Index"><i class="bi bi-diagram-3"></i> Todos os Setores</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        }

                        @if (ViewBag.TipoPerfil == 1)
                        {
                            <div class="accordion accordion-flush" id="accordionFuncionarios">
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOneFuncionarios" aria-expanded="false" aria-controls="flush-collapseOne">
                                            <i class="bi bi-people" style="padding-right:5px;"></i> Funcionários
                                        </button>
                                    </h2>
                                    <div id="flush-collapseOneFuncionarios" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                                        <ul class="list-unstyled">
                                            <li>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Funcionarios" asp-action="Index"><i class="bi bi-diagram-3"></i> Todos os Funcionários</a>
                                            </li>
                                            <li>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Funcionarios" asp-action="Criar"><i class="bi bi-person-plus"></i> Cadastrar Novo Funcionário</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        }

                        @if (ViewBag.TipoPerfil == 1)
                        {
                            <div class="accordion accordion-flush" id="accordionUsuarios">
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOneUsuarios" aria-expanded="false" aria-controls="flush-collapseOne">
                                            <i class="bi bi-person-gear" style="padding-right:5px;"></i> Usuários
                                        </button>
                                    </h2>
                                    <div id="flush-collapseOneUsuarios" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                                        <ul class="list-unstyled">
                                            <li>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index"><i class="bi bi-diagram-3"></i> Todos os Usuários</a>
                                            </li>
                                            <li>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Cadastrar"><i class="bi bi-person-plus"></i> Cadastrar Novo Usuário</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Home" asp-action="Privacy"><i class="bi bi-shield-lock"></i> Privacidade</a>
                        </li>
                </ul>
            </div>

            <footer class="border-top footer text-muted"  >
                <div class="container">
                    &copy; 2025 - TCBSistemaDeControle - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        </div>

    

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*     <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TCBSistemaDeControle - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    @* <script src="~/js/security.js"></script> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>